theme: jekyll-theme-slate
title: Andrew Mayer. CV.
description: iOS engineer > since 2013 (10 years)

darkmode: true

twitter_username: dddronnn
github_username:  Dronnn
stackoverflow_username: "1730842"
facebook_username: dddronnn
instagram_username: dronnn
linkedin_username: andreymayer
